# helmrelease-nginx.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-server
  namespace: nginx
spec:
  releaseName: nginx-server
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.1.2"  # Specify the chart version you want to use
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
      port: 80
