apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-applications
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/infrastructure/applications
  prune: true
  patches:
    - target:
        kind: HelmRelease
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: all-helm-release
        spec:
          driftDetection:
            mode: enabled
            ignore:
              - paths:
                  - "/spec/replicas"
                  - "/spec/template/spec/containers/0/resources"
