apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: infrastructure-applications
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/tenants/applications
  prune: true
  patches:
    - target:
        kind: Kustomization
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: all-kustomization
        spec: 
          patches:
            - target:
                kind: HelmRelease
              patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2beta1
                kind: HelmRelease
                metadata:
                  name: all-helm-release
                spec:
                  driftDetection:
                    mode: warn
                    ignore:
                      - paths:
                          - "/spec/replicas"
                          - "/spec/template/spec/containers/0/resources"
