apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: infrastructure-applications
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/tenants/applications
  prune: true
  patches:
    - target:
        kind: Kustomization
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: all-kustomization
        spec: 
          patches:
            - target:
                kind: HelmRelease
              patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2beta1
                kind: HelmRelease
                metadata:
                  name: all-helm-release
                spec:
                  driftDetection:
                    mode: enabled
                    ignore:
                      - paths:
                          - "/spec/replicas"
                          - "/spec/template/spec/initContainers/0/resources"
                          - "/spec/template/spec/initContainers/1/resources"
                          - "/spec/template/spec/initContainers/2/resources"
                          - "/spec/template/spec/initContainers/3/resources"
                          - "/spec/template/spec/initContainers/4/resources"
                          - "/spec/template/spec/containers/0/resources"
                          - "/spec/template/spec/containers/1/resources"
                          - "/spec/template/spec/containers/2/resources"
                          - "/spec/template/spec/containers/3/resources"
                          - "/spec/template/spec/containers/4/resources"
                          - "/spec/template/spec/containers/5/resources"
                          - "/spec/template/spec/containers/6/resources"
                          - "/spec/template/spec/containers/7/resources"
                          - "/spec/template/spec/containers/8/resources"
                          - "/spec/template/spec/containers/9/resources"
                      - paths:
                          - "/spec/metrics"
                          - "/spec/minReplicas"
                          - "/spec/maxReplicas"
                          - "/spec/behavior"
                        target:
                          kind: HorizontalPodAutoscaler
