---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        nodegroup: infra
        team: ops
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        nodegroup: infra
        team: ops
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        nodegroup: infra
        team: ops
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        nodegroup: infra
        team: ops
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: ops
