apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-2
  namespace: redis-2
spec:
  interval: 1m
  chart:
    spec:
      chart: redis
      version: "17.11.6" # Specify your desired version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Add your specific configuration values here
    architecture: replication  # Changed from standalone to replication
    auth:
      enabled: true
      password: "password"
    master:
      persistence:
        enabled: true
        size: 8Gi
    replica:
      replicaCount: 3  
      persistence:
        enabled: true
        size: 8Gi
