apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "17.11.3"  # Specify your desired version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Add your specific configuration values here
    architecture: replication  # Changed from standalone to replication
    auth:
      enabled: true
      password: "password"
    replica:
      replicaCount: 1    # This will create 1 master + 1 replica
    master:
      persistence:
        enabled: true
        size: 8Gi
    replica:
      persistence:
        enabled: true
        size: 8Gi