apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gotk-pdb.yaml
- helm-repository.yaml
- helm-release.yaml
- helm-release-2.yaml
patchesStrategicMerge:
- gotk-patches.yaml
- helm-release-patches.yaml
