apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tenant-app01
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/josephwarm/app02
  secretRef:
    name: flux-system
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-app02
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: tenant-app02
  prune: true
